### PR TITLE
Clarify "please flush object cache" message in multisite to mention cached lookup value

### LINKED ISSUE #12: Clarify "please flush object cache" message in multisite
After running `search-replace` on multisite with a persistent object cache enabled, you can see a message like this:

```
Success: Made 2419 replacements. Please remember to flush your persistent object cache with `wp cache flush`
```

However, running `wp cache flush` may produce a "Error: site not found" message if the old lookup value is still in cache.

Et voila! You've entered an indeterminate state where you'd expect you could flush cache against the new URL, but the cache still has the old URL, so you need to flush cache against the old URL before the new URL works.

We should clarify the message accordingly when this scenario occurs.

### PR DESCRIPTION
**Pull request by Sidsector9**
Fixes #12

### CODE REVIEW

File: src/Search_Replace_Command.php [hunk 1]
```diff
@@ -258,7 +258,7 @@ public function __invoke( $args, $assoc_args ) {
 			} else {
 				$success_message = "Made $total replacements.";
 				if ( $total && 'Default' !== WP_CLI\Utils\wp_get_cache_type() ) {
-					$success_message .= ' Please remember to flush your persistent object cache with `wp cache flush`.';
+					$success_message .= ' Please remember to flush your persistent object cache with `wp cache flush`. If you see a "Site not found" error after replacing a domain, try flushing cache against the old domain (which may be the cached lookup value).';
```
Comment (danielbachhuber) [inline src/Search_Replace_Command.php]: The "If you see..." clarification should only be included when `is_multisite()` is true, because it's not applicable for single site.

**Comment by Sidsector9** [comment]
@schlessera You're right, I missed it! Changes made.

File: src/Search_Replace_Command.php [hunk 2]
```diff
@@ -258,7 +258,10 @@ public function __invoke( $args, $assoc_args ) {
 			} else {
 				$success_message = "Made $total replacements.";
 				if ( $total && 'Default' !== WP_CLI\Utils\wp_get_cache_type() ) {
-					$success_message .= ' Please remember to flush your persistent object cache with `wp cache flush`.';
+						$success_message .= ' Please remember to flush your persistent object cache with `wp cache flush`.';
```
Comment (schlessera) [inline src/Search_Replace_Command.php]: Indentation is off here.
